### ISSUE TITLE
Can't convert true into String

### ISSUE THREAD

**Issue by gjedeer** [lazzarello/chef-twelvetone#1]
I'm encountering the following error when running on Ubuntu

 cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=11.04
DISTRIB_CODENAME=natty
DISTRIB_DESCRIPTION="Ubuntu 11.04"
# chef-solo -c client.solo.rb -j config-freeswitch.json

[Tue, 17 Jul 2012 19:41:24 +0200] INFO: Starting Chef Solo Run
[Tue, 17 Jul 2012 19:41:27 +0200] INFO: Replacing the run_list with ["recipe[freeswitch]"] from JSON
/root/chef-twelvetone/cookbooks/freeswitch/recipes/default.rb:87:in `system': can't convert true into String (TypeError)
        from /root/chef-twelvetone/cookbooks/freeswitch/recipes/default.rb:87:in`from_file'
        from /usr/lib/ruby/1.8/chef/mixin/recipe_definition_dsl_core.rb:73:in `instance_eval'
        from /usr/lib/ruby/1.8/chef/mixin/recipe_definition_dsl_core.rb:73:in`method_missing'
        from /root/chef-twelvetone/cookbooks/freeswitch/recipes/default.rb:86:in `from_file'
        from /usr/lib/ruby/1.8/chef/cookbook.rb:171:in`load_recipe'
        from /usr/lib/ruby/1.8/chef/mixin/language_include_recipe.rb:41:in `include_recipe'
        from /usr/lib/ruby/1.8/chef/mixin/language_include_recipe.rb:26:in`each'
        from /usr/lib/ruby/1.8/chef/mixin/language_include_recipe.rb:26:in `include_recipe'
        from /usr/lib/ruby/1.8/chef/compile.rb:145:in`load_recipes'
        from /usr/lib/ruby/1.8/chef/compile.rb:144:in `each'
        from /usr/lib/ruby/1.8/chef/compile.rb:144:in`load_recipes'
        from /usr/lib/ruby/1.8/chef/compile.rb:54:in `initialize'
        from /usr/lib/ruby/1.8/chef/client.rb:329:in`new'
        from /usr/lib/ruby/1.8/chef/client.rb:329:in `converge'
        from /usr/lib/ruby/1.8/chef/client.rb:108:in`run_solo'
        from /usr/lib/ruby/1.8/chef/application/solo.rb:198:in `run_application'
        from /usr/lib/ruby/1.8/chef/application/solo.rb:190:in`loop'
        from /usr/lib/ruby/1.8/chef/application/solo.rb:190:in `run_application'
        from /usr/lib/ruby/1.8/chef/application.rb:62:in`run'
        from /usr/bin/chef-solo:24

**Comment by lazzarello** [comment]
This is odd. It's not parsing the boolean correctly. What version of Chef are you running? I have tested these recipes against the "opscode full stack" version of Chef with Ruby 1.9. The 12 step program for this cookbook is published on the guardian project blog. https://guardianproject.info/2012/05/17/build-your-own-open-secure-telephony-network-some-assembly-required/

**Comment by gjedeer** [comment]
Oh, thanks for the step by step instructions, I'll just use them. But for completeness:

gdr:~$ chef-solo -vChef: 0.8.16
gdr:~$ ruby -v
ruby 1.8.7 (2010-08-16 patchlevel 302) [i686-linux]
gdr:~$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=11.04
DISTRIB_CODENAME=natty
DISTRIB_DESCRIPTION="Ubuntu 11.04"

**Comment by lazzarello** [comment]
Ah. I tested the cookbook against version 0.10. You should be able to put
quotes around the boolean in the mean time. I'll test a fix later tonight.

Thanks for the input.

-lee
On Jul 21, 2012 6:51 AM, "GDR!" <
reply@reply.github.com>
wrote:

**Comment by lazzarello** [comment]
I pushed a change. See if that helps. FWIW, it looks like there's a data type compatibility problem with version 0.8, as the current documentation says booleans are a valid type.

http://wiki.opscode.com/display/chef/Resources#Resources-User

**Comment by lazzarello** [comment]
I'm closing this since the official instruction now depend on Chef 0.10 and use the Opscode installer to get it on the system.
